Homework #1, Task 1-5
SiarheiTuzhyk/AT-2016-1 pull request #1
Opened 2016-10-02 17:14 UTC by SiarheiTuzhyk

2016-10-02 19:16 UTC, AlexanderSoroka requested changes

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +//package Homework_1;
Avoid unused commented code

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +    public static void main(String[] args){
Missed comment for main

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +        // Initialization of parameters
Local variables should be declared closer to it first use

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +        if(args.length > 2)
{} brackets missed

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +            System.out.println("Input more than two numbers.");
Application can stop here and call System.exit

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +        else{
Missed space else {

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +            firstNumber = Double.parseDouble(args[0]);
If I call your application with arguments 1 blablabla it will stop with unhanded exception

2016-10-02 19:16 UTC, AlexanderSoroka commented on Calculator.java
> +            ";\nComposition of two numbers: " + composition + ";\nDivision of two numbers: " + division + ";");
Salary example - if I run it with arguments 1 0 it'll print something like NaN

2016-10-02 19:16 UTC, AlexanderSoroka commented on CommandLineName.java
> +    public static void main(String[] args){
Missed comment for main

2016-10-02 19:16 UTC, AlexanderSoroka commented on CommandLineParams.java
> +
Delete this blank line

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    public static void main(String[] args){
Missed comment

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +
Useless blank line

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +        double a;
Declare local variable closer to first use

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +            System.out.print("You entered 'a' = 0.\nThanks for all :)");
Avoid jokes, emoticons and emotions in your code.

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +            System.exit(0);
System.exit(0); means that application finished successfully that is wrong Please take a look to documentation

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +        b = scanner.nextDouble();
Extract this piece of code to separate method

2016-10-02 19:16 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +        else if(delta == 0){
http://www.java67.com/2015/09/float-and-double-value-comparison-in-java-use-relational.html

2016-10-02 19:16 UTC, AlexanderSoroka commented on Triangle.java
> +    public static void main (String[] args){
Missed comment

2016-10-02 19:16 UTC, AlexanderSoroka commented on Triangle.java
> +        a = scanner.nextDouble();
Extract this to separate method

2016-10-02 19:16 UTC, AlexanderSoroka commented on Triangle.java
> +        else
missed {}

2016-10-03 07:55 UTC, AlexanderSoroka requested changes

2016-10-03 07:55 UTC, AlexanderSoroka commented on Calculator.java
> +        } else {
Useless else

2016-10-03 07:55 UTC, AlexanderSoroka commented on Calculator.java
> +                double amount;
It's better to write:
double amount = calculateAmount(firstNumber, secondNumber);

2016-10-03 07:55 UTC, AlexanderSoroka commented on Calculator.java
> +        if (second < 0.00001 && second > -0.00001) {
It should be performed not in this method

2016-10-03 13:07 UTC, AlexanderSoroka requested changes

2016-10-03 13:07 UTC, AlexanderSoroka commented on Calculator.java
> +            if(Double.isInfinite(division)) {
what about NaN?

2016-10-03 19:40 UTC, AlexanderSoroka requested changes

2016-10-03 19:40 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +public class QuadraticEquation {
Missed class comment

2016-10-03 19:40 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    public static final double EPS = 10e-15;
Why this value?

2016-10-03 19:40 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    // This method required for the use of methods to input the coefficients of quadratic equation and finding roots.
Comment must be javadoc

2016-10-03 20:34 UTC, AlexanderSoroka requested changes

2016-10-03 20:34 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    public static final double EPS = 10e-15;
Why do you think that this value is acceptably close to 0?

2016-10-03 20:34 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    /**
Insert blank line prior comment

2016-10-03 20:34 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +                if (i == 0) {
This check will be performed on each iteration but plays role only for the i == 0; it definitly must be outside cycle

2016-10-03 20:34 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +            System.out.println("I/O error.\nThanks for all.");
I/O always means file, stream etc input\output operations

2016-10-03 20:56 UTC, SiarheiTuzhyk commented on QuadraticEquation.java
> +    public static final double EPS = 10e-15;
Because we haven't used calculations with floating-point numbers, where we need filigree accuracy. For this we could take another number, more than 10e-15.

2016-10-04 07:07 UTC, AlexanderSoroka requested changes

2016-10-04 07:07 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +    public static final double EPS = 10e-15;
The third time (if I'm not mistaken) why 10e-15? what if user want to calculate roots of equation with very smal coeffs?

2016-10-04 07:07 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +                System.out.print("You entered 'a' = 0.\nThanks for all.");
what if user enter 10e-16?

2016-10-04 07:07 UTC, AlexanderSoroka commented on QuadraticEquation.java
> +            System.out.println("Input error.\nThanks for all.");
Does it really help user to understand what kind of input error happened?

2016-10-04 14:37 UTC, AlexanderSoroka commented
Your repository is messed a little. I'll close this pull request, you merge changes for 1-3 (but not for 4-5) to master and open new pull-request only for actuall changes for 4-5

2016-10-04 14:37 UTC, closed without merging